/*
CityPay Payment API

Testing BatchProcessingApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package citypay

import (
	"context"
	openapiclient "github.com/citypay/citypay-api-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_citypay_BatchProcessingApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BatchProcessingApiService BatchProcessRequest", func(t *testing.T) {

		resp, httpRes, err := apiClient.BatchProcessingApi.BatchProcessRequest(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchProcessingApiService BatchRetrieveRequest", func(t *testing.T) {

		resp, httpRes, err := apiClient.BatchProcessingApi.BatchRetrieveRequest(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchProcessingApiService CheckBatchStatusRequest", func(t *testing.T) {

		resp, httpRes, err := apiClient.BatchProcessingApi.CheckBatchStatusRequest(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
